### ISSUE TITLE
`mine_event` difficulty is off

### ISSUE THREAD

**Issue by plebhash** [sandwichfarm/notemine#9]
I'm doing some experiments with the code. In my local version, `fn mine_event()` returns a `MinedResult`.

Here's a broken test that makes me wonder if there's something wrong with `mine_event` function:

```rust
#[test]
    fn test_mine_event() {
        let event = NostrEvent {
            pubkey: "e771af0b05c8e95fcdf6feb3500544d2fb1ccd384788e9f490bb3ee28e8ed66f".to_string(),
            kind: 1,
            content: "hello worlda".to_string(),
            tags: vec![],
            id: None,
            created_at: Some(1668680774),
        };

        let event_json = to_string(&event).unwrap();

        let difficulty = 10;
        let mined_result = mine_event(&event_json, difficulty, 0, 1); // I modified the return type to MinedResult

        assert_eq!(mined_result.event.pubkey, event.pubkey);
        assert_eq!(mined_result.event.kind, event.kind);
        assert_eq!(mined_result.event.content, event.content);
        assert_eq!(mined_result.event.created_at, event.created_at);

        assert_eq!(mined_result.event.tags[0][0], "nonce");
        assert_eq!(mined_result.event.tags[0][2], difficulty.to_string());

        let id = mined_result.event.id.expect("expect mined_result.event.id is Some");
        let id_bytes = Vec::from_hex(id).expect("expect valid sha256 as hex");

        assert_eq!(get_pow(&id_bytes), difficulty); // panic here
    }
```

and the test logs:
```
test tests::test_mine_event ... FAILED

failures:

---- tests::test_mine_event stdout ----
thread 'tests::test_mine_event' panicked at src/lib.rs:215:9:
assertion `left == right` failed
  left: 11
 right: 10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by plebhash** [comment]
with different difficulties:

```
---- tests::test_mine_event stdout ----
thread 'tests::test_mine_event' panicked at src/lib.rs:215:9:
assertion `left == right` failed
  left: 23
 right: 21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So I guess there's no real issue here. This is just a consequence of the statistical nature of PoW.

I just need to change my assertion to:
```diff
- assert_eq!(get_pow(&id_bytes), difficulty); // panic here
+ assert!(get_pow(&id_bytes) >= difficulty); // always correct
```
